export const SET_CLIENTS = 'SET_CLIENTS';
export const SET_SELECTED_CLIENT = 'SET_SELECTED_CLIENT';

export const SET_QUOTATIONS = 'SET_QUOTATIONS';
export const SET_SELECTED_QUOTATION = 'SET_SELECTED_QUOTATION';

export const SET_CONFIGURATIONS = 'SET_CONFIGURATIONS';
export const SET_SELECTED_CONFIGURATION = 'SET_SELECTED_CONFIGURATION';

export const ADD_CLICHE = 'ADD_CLICHE';
export const DELETE_CLICHE = 'DELETE_CLICHE';
export const ADD_FOIL = 'ADD_FOIL';
export const DELETE_FOIL = 'DELETE_FOIL';
export const ADD_STEP = 'ADD_STEP';
export const DELETE_STEP = 'DELETE_STEP';
export const SET_FOIL_OFFSETS = 'SET_FOIL_OFFSETS';
export const ADD_QUOTATION_INSTANCE = 'ADD_QUOTATION_INSTANCE';
export const DELETE_QUOTATION_INSTANCE = 'DELETE_QUOTATION_INSTANCE';
export const CUSTOMIZE_QUOTATION_INSTANCE_FOIL_PRICE = 'CUSTOMIZE_QUOTATION_INSTANCE_FOIL_PRICE';
export const CUSTOMIZE_QUOTATION_INSTANCE_CLICHE_PRICE = 'CUSTOMIZE_QUOTATION_INSTANCE_CLICHE_PRICE';
export const CUSTOMIZE_QUOTATION_INSTANCE_PRODUCTION_PRICE = 'CUSTOMIZE_QUOTATION_INSTANCE_PRODUCTION_PRICE';
// export const SET_QUOTATION_INSTANCE_OBSERVATIONS = 'SET_QUOTATION_INSTANCE_OBSERVATIONS';

export const SET_LOADING = 'SET_LOADING';
