export const SET_CLIENTS = 'SET_CLIENTS';
export const SET_SELECTED_CLIENT = 'SET_SELECTED_CLIENT';

export const SET_QUOTATIONS = 'SET_QUOTATIONS';
export const SET_SELECTED_QUOTATION = 'SET_SELECTED_QUOTATION';

